# Generated by Django 5.2 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, default='', help_text='Comma-separated colors or custom input', max_length=255, null=True),
        ),
    ]
