# Generated by Django 5.2 on 2025-04-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_remove_product_available_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
