# Generated by Django 5.2 on 2025-04-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
