# Generated by Django 5.2 on 2025-04-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_cartitem_color_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='special_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.specialoffer'),
        ),
    ]
