# Generated by Django 5.2 on 2025-05-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cartitem_special_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('interaction_type', models.CharField(choices=[('view', 'Product View'), ('search_click', 'Search Click'), ('wishlist', 'Added to Wishlist'), ('cart', 'Added to Cart')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'session_key'], name='store_useri_user_id_887176_idx'), models.Index(fields=['product'], name='store_useri_product_e9772e_idx'), models.Index(fields=['interaction_type'], name='store_useri_interac_bbdc72_idx')],
            },
        ),
    ]
