# Generated by Django 5.2 on 2025-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Product View'), ('search_click', 'Search Click'), ('wishlist', 'Added to Wishlist'), ('cart', 'Added to Cart'), ('category_view', 'Category View')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
